# Generated by Django 5.1.4 on 2024-12-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(default='Trip details'),
            preserve_default=False,
        ),
    ]
